port: 8080
endpoints:
  - path: /test
    method: GET
    async: false
    container:
      image: hello-world
  - path: /async
    method: GET
    async: true
    container:
      image: busybox
      command:
        - echo
        - hello
  - path: /hello
    method: GET
    async: false
    params:
      - name: fullname
        optional: false
    container:
      image: ubuntu
      command:
        - "bash"
        - "-c"
        - "echo hello, {{ fullname }}"
  - path: /post
    method: POST
    async: true
    params:
      - name: fullname
        optional: true
    container:
      image: busybox
      command:
        - echo
        - "{{ fullname }}"
