port: 8080
healthcheckPath: /health
endpoints:
  - path: /test
    method: GET
    container:
      image: hello-world
  - path: /async
    method: GET
    async: true
    container:
      image: busybox
      command:
        - echo
        - hello
  - path: /hello
    method: GET
    params:
      - name: fullname
    container:
      image: docker.io/library/ubuntu
      command:
        - "bash"
        - "-c"
        - "echo hello, {{ fullname }}"
  - path: /hello_with_env
    method: GET
    params:
      - name: fullname
    env:
      - GREET
    container:
      image: ubuntu
      command:
        - "bash"
        - "-c"
        - "echo $GREET, {{ fullname }}"
  - path: /post
    method: POST
    async: true
    params:
      - name: fullname
        optional: true
    container:
      image: busybox
      command:
        - echo
        - "{{ fullname }}"
