apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cgw
  name: container-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgw
  template:
    metadata:
      labels:
        app: cgw
    spec:
      containers:
      - image: takutakahashi/continer-api-gateway
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
