kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: job-admin
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "update", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: job-admin-binding
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: job-admin
  apiGroup: rbac.authorization.k8s.io
