apiVersion: v1
kind: Service
metadata:
  labels:
    app: cgw
  name: container-api-gateway
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cgw
